name: Hello world
on: 
  push:
   - main


jobs:
  hello-job:
  runs-on: ubuntu-latest

  steps:
    - name: checkout to main branch
      uses: actions/checkout@v4

    - name: Echo text
      run: echo "Hello, world!"


  









































































































































































































































































































































